
name: CMake on Windows

on:
  push:
    branches: [ $default-branch ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with: 
        msystem: mingw64
        install: >-
          mingw-w64-ucrt-x86_64-gcc
          cmake
          make
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Configure CMake
      run: cmake .

    - name: Build
      run: ./build.sh

    - name: Archive
      uses: actions/upload-artifact@v4
      with:
        name: RTFIR
        path: |
          filters
          RTFIR.exe
