
name: CMake on Windows

on:
  push:
    branches: [ $default-branch ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    vcpkg_triplet: x64-mingw-static

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake .

    - name: Build
      run: cmake --build .

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: RTFIR.exe
        path: RTFIR.exe
