
name: CMake on Windows 2

on:
  workflow_dispatch:

jobs:
  one:
    runs-on: windows-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: 'port'
        submodules: recursive

    - name: Run
      run: type build.txt>build.bat&build

    - name: Archive
      uses: actions/upload-artifact@v4
      with:
        path: |
          build/Release/bin/RTFIR.exe
